import streamlit as st
import json
import pandas as pd

# Load the JSON summaries
@st.cache_data
def load_json(path):
    with open(path, 'r') as f:
        return json.load(f)

# Paths to your generated JSON files
THEME_SUMMARY_PATH = 'review_theme_summary.json'
BERT_LIKES_PATH   = 'bertinsights_likes.json'
BERT_DISLIKES_PATH= 'bertinsights_dislikes.json'

# Load data
theme_summary = load_json(THEME_SUMMARY_PATH)
bert_likes    = load_json(BERT_LIKES_PATH)
bert_dislikes = load_json(BERT_DISLIKES_PATH)

# Sidebar filters
game_filter = st.sidebar.text_input("Game ID or Name Filter", '')

st.title("🎮 Game Review Insights Dashboard")

# 1) Theme Mentions
st.header("Theme Mention Counts")
counts = theme_summary['theme_counts']
counts_series = pd.Series(counts).sort_values(ascending=False)
st.bar_chart(counts_series)

# 2) Top Reviews by Theme
st.header("Top Reviews by Theme")
for theme, reviews in theme_summary['top_reviews'].items():
    with st.expander(theme.title()):
        for rev in reviews:
            st.markdown(f"**Votes:** {rev['votes_up']}")
            st.write(rev['review'])
            st.markdown("---")

# 3) BERTopic - What Players Like
st.header("BERTopic Insights: What Players LIKE")
for topic_id, terms in bert_likes.items():
    with st.expander(f"Topic {topic_id}"):
        st.write(", ".join([t for t, _ in terms]))

# 4) BERTopic - What Players DISLIKE
st.header("BERTopic Insights: What Players DISLIKE")
for topic_id, terms in bert_dislikes.items():
    with st.expander(f"Topic {topic_id}"):
        st.write(", ".join([t for t, _ in terms]))

# 5) Quick Takeaways
st.header("🚀 Quick Takeaways")
st.markdown("- **Top themes**: " + ", ".join(counts_series.head(3).index.tolist()))
st.markdown("- **Emerging positive topics**: " + ", ".join([", ".join([t for t,_ in bert_likes[str(t)]]) for t in list(bert_likes.keys())[:3]]))
st.markdown("- **Emerging negative topics**: " + ", ".join([", ".join([t for t,_ in bert_dislikes[str(t)]]) for t in list(bert_dislikes.keys())[:3]]))

# Footer
st.markdown("---")
st.caption("Insights generated by Dask + BERTopic pipeline")
